# Generated by Django 5.1.5 on 2025-10-30 20:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(help_text='Short description for card view')),
                ('long_description', models.TextField(blank=True, help_text='Detailed description for project page')),
                ('tags', models.JSONField(default=list, help_text='List of technology tags')),
                ('image_url', models.URLField(help_text='Main project image', max_length=500)),
                ('gallery_images', models.JSONField(default=list, help_text='List of image URLs for slideshow')),
                ('live_url', models.URLField(blank=True, max_length=500, null=True)),
                ('github_url', models.URLField(blank=True, max_length=500, null=True)),
                ('is_ai_feature', models.BooleanField(default=False)),
                ('is_featured', models.BooleanField(default=True, help_text='Show on home page')),
                ('order', models.IntegerField(default=0, help_text='Display order')),
                ('slug', models.SlugField(help_text='URL-friendly identifier', max_length=200, unique=True)),
            ],
            options={
                'ordering': ['order', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('svg_icon', models.TextField(help_text='SVG markup for the skill icon')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProjectSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_featured', models.BooleanField(default=False, help_text='Show this skill on home page for this project')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.project')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.skill')),
            ],
            options={
                'ordering': ['-is_featured', 'skill__name'],
                'unique_together': {('project', 'skill')},
            },
        ),
        migrations.AddField(
            model_name='project',
            name='skills',
            field=models.ManyToManyField(blank=True, related_name='projects', through='portfolio.ProjectSkill', to='portfolio.skill'),
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=200)),
                ('role', models.CharField(max_length=200)),
                ('period', models.CharField(help_text='e.g., Jan 2020 - Dec 2022', max_length=100)),
                ('description', models.JSONField(default=list, help_text='List of job responsibilities/achievements')),
                ('order', models.IntegerField(default=0, help_text='Display order')),
                ('skills', models.ManyToManyField(blank=True, related_name='experiences', to='portfolio.skill')),
            ],
            options={
                'ordering': ['order', '-id'],
            },
        ),
    ]
