# Generated by Django 5.1.5 on 2025-10-30 21:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='gallery_images',
        ),
        migrations.AddField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, help_text='Upload main project image', null=True, upload_to='projects/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='image_url',
            field=models.URLField(blank=True, help_text='Or provide image URL (used if no upload)', max_length=500),
        ),
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Upload gallery image', upload_to='gallery/')),
                ('image_url', models.URLField(blank=True, help_text='Or provide image URL', max_length=500)),
                ('order', models.IntegerField(default=0, help_text='Display order in gallery')),
                ('caption', models.CharField(blank=True, help_text='Optional image caption', max_length=200)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='portfolio.project')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
