# Generated by Django 4.2.7 on 2025-11-21 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_alter_skill_options_skill_is_featured_skill_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='order',
            field=models.IntegerField(db_index=True, default=0, help_text='Display order (lower numbers first)'),
        ),
        migrations.CreateModel(
            name='ProjectLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(help_text="e.g., 'Live Site', 'GitHub', 'Documentation'", max_length=100)),
                ('url', models.URLField(max_length=500)),
                ('order', models.IntegerField(default=0, help_text='Display order')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='portfolio.project')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
