# Generated by Django 4.2.7 on 2025-11-21 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_alter_skill_order_projectlink'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectlink',
            name='svg_icon',
            field=models.TextField(blank=True, help_text='SVG markup for the link icon'),
        ),
        migrations.AlterField(
            model_name='project',
            name='github_url',
            field=models.URLField(blank=True, help_text='URL to GitHub repository', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='live_url',
            field=models.URLField(blank=True, help_text='URL to live project', max_length=500, null=True),
        ),
    ]
