# Generated by Django 4.2.7 on 2025-11-21 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_projectlink_svg_icon_alter_project_github_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='github_url',
        ),
        migrations.RemoveField(
            model_name='project',
            name='live_url',
        ),
    ]
